version: 0.0
os: linux

files:
  - source: /
    destination: /opt/ec2-app

permissions:
  - object: /opt/ec2-app
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
  - object: /var/log/ec2-app.log
    owner: ec2-user
    group: ec2-user
    mode: 664

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 180
      runas: root

  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root

  Install:
    - location: scripts/install.sh
      timeout: 600
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 120
      runas: root
